### ISSUE TITLE
Error in controls.py

### ISSUE THREAD

**Issue by maquirag** [friendsofiron/PlatformGameProject-py#1]
py controls.py
```python
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "controls.py", line 168, in <module>
    __Testings("Controls")
  File "controls.py", line 83, in __init__
    c.update()
  File "controls.py", line 134, in update
    self.current["events"] = self.pygame.event.get()
AttributeError: 'str' object has no attribute 'event'
```

**Comment by SebTheS** [comment]
It is now fixed. Thanks.

**Comment by maquirag** [comment]
now there is a different error :)
```python
Traceback (most recent call last):
  File "controls.py", line 168, in <module>
    __Testings("Controls")
  File "controls.py", line 79, in __init__
    c = Controls(python, "adsw")
NameError: name 'python' is not defined
```

**Comment by SebTheS** [comment]
Fixed.
